---
title: "Example"
author: "Miles Williams"
date: "June 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message = F,
                      warning = F)
```

Let's play around with `tidyverse`.

```{r tidyverse}
library(tidyverse)
library(gapminder)
```

```{r look at gapminder}
gapminder
```

```{r pipes}
sqrt(4) # base R
4 %>% sqrt() # with piping

# With ln
log(sqrt(4))
4 %>% sqrt() %>% log()

# can save things (object assignment)
my_object = 4 %>% sqrt() %>% log()

# reverse assignment!
4 %>% sqrt() %>% log() -> my_object


# create a pipeline with gapminder data
gapminder %>% 
  filter(year == 2002) %>%
  mutate(gdp = pop * gdpPercap) -> 
  gapminder_2002

ggplot(data = gapminder_2002) + 
  aes(x = gdpPercap) + 
  aes(y = lifeExp) + 
  geom_point() + 
  aes(col = continent) + 
  aes(size = pop/1000000) + 
  scale_x_log10(breaks=c(400,4000,40000),
                labels = scales::comma) + 
  labs(x = "GDP per capita\n($US)",
       y = "Life Expectancy\n(Years)",
       title = "Health and Wealth",
       subtitle = "Data for 2002",
       col="",
       size = "Population (millions)")

last_plot() + 
  theme_classic()
```

